# Generated by Django 4.2 on 2026-01-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0017_alter_formfield_choices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['section__order', 'section__id', 'order', 'column', 'id']},
        ),
        migrations.AddField(
            model_name='formfield',
            name='column',
            field=models.PositiveIntegerField(default=1, help_text='Column number within the section (1, 2, 3, etc.)'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='column_width',
            field=models.PositiveIntegerField(blank=True, help_text='Column width percentage (optional, for flexible layouts)', null=True),
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Section name (e.g., 'General Section')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional section description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of section within the form')),
                ('is_collapsible', models.BooleanField(default=False, help_text='Allow users to collapse/expand this section')),
                ('columns', models.PositiveIntegerField(default=1, help_text='Number of columns in this section (1-4)')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ticketflow.form')),
            ],
            options={
                'verbose_name': 'Form Section',
                'verbose_name_plural': 'Form Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section this field belongs to (leave empty for no section)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='ticketflow.formsection'),
        ),
    ]
