# Generated by Django 4.2 on 2026-01-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0018_alter_formfield_options_formfield_column_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['tab__order', 'tab__id', 'section__order', 'section__id', 'order', 'column', 'id']},
        ),
        migrations.AlterModelOptions(
            name='formsection',
            options={'ordering': ['tab__order', 'tab__id', 'order', 'id'], 'verbose_name': 'Form Section', 'verbose_name_plural': 'Form Sections'},
        ),
        migrations.AlterField(
            model_name='formsection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of section within the tab/form'),
        ),
        migrations.CreateModel(
            name='FormTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tab name (e.g., 'General', 'Risk')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional tab description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of tab within the form')),
                ('icon', models.CharField(blank=True, help_text="Optional icon class or name (e.g., 'fa-home', 'icon-general')", max_length=50)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='ticketflow.form')),
            ],
            options={
                'verbose_name': 'Form Tab',
                'verbose_name_plural': 'Form Tabs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='tab',
            field=models.ForeignKey(blank=True, help_text='Tab this field belongs to (only if field is not in a section)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='ticketflow.formtab'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='tab',
            field=models.ForeignKey(blank=True, help_text='Tab this section belongs to (leave empty for no tab)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='ticketflow.formtab'),
        ),
    ]
